Repository kubernetes-sigs/multicluster-runtime, pull requests merged in 2025-07, with the labels that each got.

#45 🌱 Kubeconfig-Based Provider
  examples/kubeconfig/README.md
  examples/kubeconfig/go.mod
  examples/kubeconfig/go.sum
  examples/kubeconfig/main.go
  examples/kubeconfig/scripts/create-kubeconfig-secret.sh
  examples/kubeconfig/scripts/rules.yaml
  providers/kubeconfig/kubeconfig_suite_test.go
  providers/kubeconfig/provider.go
  providers/kubeconfig/provider_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#26 🌱 Contribute Kubeconfig-Based Provider
  examples/kubeconfig/README.md
  examples/kubeconfig/controllers/pod_lister.go
  examples/kubeconfig/main.go
  examples/kubeconfig/scripts/create-kubeconfig-secret.sh
  providers/kubeconfig/provider.go
Labels: cncf-cla: yes, size/XL, do-not-merge/work-in-progress

#48 🌱 Cluster Inventory(`ClusterProfile`) API Provider
  .github/workflows/ci.yml
  Makefile
  examples/cluster-inventory-api/clusterprofile-provider-file.json
  examples/cluster-inventory-api/go.mod
  examples/cluster-inventory-api/go.sum
  examples/cluster-inventory-api/main.go
  hack/check-everything.sh
  hack/test-all.sh
  providers/cluster-inventory-api/go.mod
  providers/cluster-inventory-api/go.sum
  providers/cluster-inventory-api/kubeconfigstrategy/credentialsprovider.go
  providers/cluster-inventory-api/kubeconfigstrategy/factory.go
  providers/cluster-inventory-api/kubeconfigstrategy/interface.go
  providers/cluster-inventory-api/kubeconfigstrategy/secret.go
  providers/cluster-inventory-api/provider.go
  providers/cluster-inventory-api/provider_test.go
  providers/cluster-inventory-api/suite_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#57 ✨ enhancement: kubeconfig provider support more params
  providers/kubeconfig/provider.go
  providers/kubeconfig/provider_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm
