Repository kubernetes-sigs/multicluster-runtime, pull requests merged in 2025-08, with the labels that each got.

#53 ✨ Add `file` provider for kubeconfig on the filesystem
  .github/workflows/ci.yml
  examples/file/README.md
  examples/file/go.mod
  examples/file/go.sum
  examples/file/main.go
  providers/file/clusters.go
  providers/file/file_suite_test.go
  providers/file/go.mod
  providers/file/go.sum
  providers/file/provider.go
  providers/file/provider_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#67 🌱 Use mcmanager.Options instead of manager.Options where applicable
  alias.go
  examples/cluster-api/main.go
  examples/cluster-inventory-api/main.go
  examples/kind/main.go
  examples/kubeconfig/main.go
  examples/namespace/main.go
  pkg/manager/manager.go
  providers/cluster-inventory-api/provider_test.go
  providers/namespace/provider_test.go
Labels: cncf-cla: yes, approved, lgtm, size/S

#61 :seedling: Stop setting tags on example modules
  hack/release-commit.sh
Labels: size/XS, cncf-cla: yes, approved, lgtm

#68 :seedling: Prepare release for sigs.k8s.io/multicluster-runtime@v0.21.0-alpha.9
  examples/cluster-api/go.mod
  examples/cluster-inventory-api/go.mod
  examples/file/go.mod
  examples/kind/go.mod
  examples/kubeconfig/go.mod
  providers/cluster-api/go.mod
  providers/cluster-inventory-api/go.mod
  providers/file/go.mod
  providers/kind/go.mod
Labels: cncf-cla: yes, approved, lgtm, size/S
