Repository kubernetes-sigs/multicluster-runtime, pull requests merged in 2025-03, with the labels that each got.

#20 :seedling: Rename to sigs.k8s.io/multicluster-runtime go module
  .golangci.yml
  README.md
  alias.go
  examples/cluster-api/go.mod
  examples/cluster-api/main.go
  examples/kind/go.mod
  examples/kind/main.go
  examples/namespace/main.go
  go.mod
  internal/forked/testing/addr/manager.go
  internal/forked/testing/addr/manager_test.go
  pkg/builder/forked_builder_suite_test.go
  pkg/builder/forked_controller.go
  pkg/builder/forked_controller_test.go
  pkg/context/cluster.go
  pkg/controller/controller.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/inject.go
  pkg/handler/lift.go
  pkg/manager/manager.go
  pkg/source/kind.go
  pkg/source/source.go
  providers/cluster-api/go.mod
  providers/cluster-api/provider.go
  providers/kind/go.mod
  providers/kind/provider.go
  providers/namespace/provider.go
  providers/namespace/provider_test.go
  providers/nop/provider.go
  providers/single/provider.go
Labels: cncf-cla: yes, size/L, ok-to-test, approved, lgtm

#23 :bug: Clean up go module names and set consistent Go version
  examples/cluster-api/go.mod
  examples/kind/go.mod
  providers/cluster-api/go.mod
  providers/kind/go.mod
Labels: cncf-cla: yes, size/M, approved, lgtm

#24 :seedling: Bump controller-runtime to v0.20.3 and Go to 1.23.7
  .github/workflows/ci.yml
  .gitignore
  Makefile
  examples/cluster-api/go.mod
  examples/cluster-api/go.sum
  examples/kind/go.mod
  examples/kind/go.sum
  go.mod
  go.sum
  providers/cluster-api/go.mod
  providers/cluster-api/go.sum
  providers/kind/go.mod
  providers/kind/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#29 📖 Minor adjustments to README, mention dynamic fleet
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/S
